WHEEL_RADIUS = 25e-3
WHEEL_LENGTH = 85e-3

# MAX_ANGULAR = 26.48 # MESTRADO FELIPE CELSO
MAX_ANGULAR = 13.0 # Valor que funcionou
MAX_WHEEL_SPEED = MAX_ANGULAR*WHEEL_LENGTH/(WHEEL_RADIUS)
MAX_VELOCITY = MAX_WHEEL_SPEED*WHEEL_RADIUS

MAX_ACC = 2.77 # TG FELIPE CELSO

POSITION_TOLERANCE = 3e-2
ANGLE_TOLERANCE = 5e-2
VELOCITY_TOLERANCE = 1e-2